server:
  jwt-key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  jwt-access-time: 10
  jwt-refresh-time: 30

#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@lotion_high?TNS_ADMIN=C:\Users\jueon\Lotion\Wallet_lotion
#    username: ADMIN
#    password: Dhfkzmf1021!