spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@lotion_high?TNS_ADMIN=/Users/sseomeon/Desktop/workspace/lotion/Wallet_lotion
    username: ADMIN
    password: Dhfkzmf1021!
mybatis:
  # config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml